from languages import languages

lang_list = [
    "af",
    "ak",
    "am",
    "ar",
    "as",
    "ay",
    "az",
    "be",
    "bg",
    "bm",
    "bn",
    "bs",
    "ca",
    "co",
    "cs",
    "da",
    "de",
    "ee",
    "el",
    "en",
    "en_1",
    "es",
    "et",
    "fa",
    "fi",
    "fr",
    "ga",
    "gu",
    "ha",
    "hi",
    "hr",
    "hu",
    "hy",
    "id",
    "ig",
    "is",
    "it",
    "iw",
    "ja",
    "jw",
    "ka",
    "kk",
    "km",
    "ko",
    "ko_1",
    "kr-deepl",
    "ku",
    "ky",
    "la",
    "lb",
    "lo",
    "lt",
    "lv",
    "mk",
    "mn",
    "ms",
    "mt",
    "my",
    "ne",
    "nl",
    "no",
    "om",
    "pa",
    "pl",
    "ps",
    "pt",
    "ro",
    "ru",
    "sa",
    "si",
    "sk",
    "sn",
    "so",
    "sq",
    "sr",
    "st",
    "sv",
    "sw",
    "ta",
    "te",
    "tg",
    "th",
    "tl",
    "tr",
    "ug",
    "uk",
    "ur",
    "uz",
    "vi",
    "zh",
    "zt",
    "zu",
]


lines = [
    "|     | Language                    | Corpus | Model en-> | Model <-en | Image Recorgnition   | Speech recognition   | speech synthesis     |",
    "| --- | --------------------------- | ------ | ---------- | ---------- | -------------------- | -------------------- | -------------------- |",
]

k = 0
for code in lang_list:

    if code in languages:
        k += 1
        name = languages[code]["en"]
        lines.append(f"| {k:<3} | {code} - {name:<22} | {"Yes":<6} | {"-":<10} | {"-":<10} | {"-":<20} | {"-":<20} | {"-":<20} |")

with open("language.md", "w", encoding="utf-8") as w:
    w.write("\n".join(lines) + '\n')
